spring.application.name=cidasdepilacao-api
spring.output.ansi.enabled=ALWAYS
api.base-url=/api/v1

# Profile ativo (troque para prod no deploy)
spring.profiles.active=dev

jwt.secret=zftSKXAYNmxbQL0EWOGcqhJ2rpZdBliy
jwt.expiration=86400000